#!/usr/bin/env python3
"""
Initialize a Docusaurus site for a repository's documentation.

Creates a Docusaurus site in .docs/<repo_name>/site with proper configuration.
"""

import argparse
import subprocess
import sys
from pathlib import Path


# Docusaurus config template
DOCUSAURUS_CONFIG = '''// @ts-check
import {{themes as prismThemes}} from 'prism-react-renderer';

/** @type {{import('@docusaurus/types').Config}} */
const config = {{
  title: '{repo_name}',
  tagline: 'Auto-generated documentation',
  favicon: 'img/favicon.ico',
  url: 'https://example.com',
  baseUrl: '/',
  organizationName: 'example',
  projectName: '{repo_name}',
  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',
  i18n: {{
    defaultLocale: 'en',
    locales: ['en'],
  }},
  markdown: {{
    mermaid: true,
  }},
  themes: ['@docusaurus/theme-mermaid'],
  presets: [
    [
      'classic',
      /** @type {{import('@docusaurus/preset-classic').Options}} */
      ({{
        docs: {{
          routeBasePath: '/',
          sidebarPath: './sidebars.js',
        }},
        blog: false,
        theme: {{
          customCss: './src/css/custom.css',
        }},
      }}),
    ],
  ],
  themeConfig:
    /** @type {{import('@docusaurus/preset-classic').ThemeConfig}} */
    ({{
      navbar: {{
        title: '{repo_name}',
        items: [
          {{
            type: 'docSidebar',
            sidebarId: 'docsSidebar',
            position: 'left',
            label: 'Documentation',
          }},
        ],
      }},
      footer: {{
        style: 'dark',
        copyright: `Auto-generated documentation`,
      }},
      prism: {{
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ['python'],
      }},
    }}),
}};

export default config;
'''

SIDEBARS_CONFIG = '''/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
'''

CUSTOM_CSS = ''':root {
  --ifm-color-primary: #2e8555;
  --ifm-color-primary-dark: #29784c;
  --ifm-color-primary-darker: #277148;
  --ifm-color-primary-darkest: #205d3b;
  --ifm-color-primary-light: #33925d;
  --ifm-color-primary-lighter: #359962;
  --ifm-color-primary-lightest: #3cad6e;
  --ifm-code-font-size: 95%;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.1);
}

[data-theme='dark'] {
  --ifm-color-primary: #25c2a0;
  --ifm-color-primary-dark: #21af90;
  --ifm-color-primary-darker: #1fa588;
  --ifm-color-primary-darkest: #1a8870;
  --ifm-color-primary-light: #29d5b0;
  --ifm-color-primary-lighter: #32d8b4;
  --ifm-color-primary-lightest: #4fddbf;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.3);
}
'''

PLACEHOLDER_INDEX = '''---
sidebar_position: 1
slug: /
---

# {repo_name} Documentation

Welcome to the auto-generated documentation for **{repo_name}**.

Run `python generate_docs.py {repo_name}` to generate the full documentation.
'''


def detect_repo_name() -> str | None:
    """Auto-detect repo name from .docs directory if there's only one."""
    docs_base = Path('.docs')
    if not docs_base.exists():
        return None
    
    repos = [d.name for d in docs_base.iterdir() if d.is_dir()]
    
    if len(repos) == 1:
        return repos[0]
    return None


def init_docusaurus_site(repo_name: str, force: bool = False):
    """Initialize a Docusaurus site for the given repo."""
    site_dir = Path('.docs') / repo_name / 'site'
    
    # Check if site already exists
    if site_dir.exists() and not force:
        print(f"Error: Site already exists at {site_dir}")
        print("Use --force to overwrite")
        return False
    
    print(f"Initializing Docusaurus site for '{repo_name}'...")
    
    # Create site directory structure
    site_dir.mkdir(parents=True, exist_ok=True)
    (site_dir / 'docs').mkdir(exist_ok=True)
    (site_dir / 'src' / 'css').mkdir(parents=True, exist_ok=True)
    (site_dir / 'static' / 'img').mkdir(parents=True, exist_ok=True)
    
    # Create a simple placeholder in static to prevent glob error
    (site_dir / 'static' / '.gitkeep').touch()
    
    # Write configuration files
    print("  Creating configuration files...")
    
    # docusaurus.config.js
    config_content = DOCUSAURUS_CONFIG.format(repo_name=repo_name)
    (site_dir / 'docusaurus.config.js').write_text(config_content)
    
    # sidebars.js
    (site_dir / 'sidebars.js').write_text(SIDEBARS_CONFIG)
    
    # custom.css
    (site_dir / 'src' / 'css' / 'custom.css').write_text(CUSTOM_CSS)
    
    # package.json
    package_json = f'''{{
  "name": "{repo_name}-docs",
  "version": "0.0.0",
  "private": true,
  "scripts": {{
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve"
  }},
  "dependencies": {{
    "@docusaurus/core": "^3.6.0",
    "@docusaurus/preset-classic": "^3.6.0",
    "@docusaurus/theme-mermaid": "^3.6.0",
    "@mdx-js/react": "^3.0.0",
    "clsx": "^2.0.0",
    "prism-react-renderer": "^2.3.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  }},
  "devDependencies": {{
    "@docusaurus/module-type-aliases": "^3.6.0",
    "@docusaurus/types": "^3.6.0"
  }},
  "browserslist": {{
    "production": [">0.5%", "not dead", "not op_mini all"],
    "development": ["last 3 chrome version", "last 3 firefox version", "last 5 safari version"]
  }},
  "engines": {{
    "node": ">=18.0"
  }}
}}
'''
    (site_dir / 'package.json').write_text(package_json)
    
    # Placeholder index page
    index_content = PLACEHOLDER_INDEX.format(repo_name=repo_name)
    (site_dir / 'docs' / 'index.md').write_text(index_content)
    
    # .gitignore for the site
    gitignore = '''node_modules/
.docusaurus/
build/
.DS_Store
'''
    (site_dir / '.gitignore').write_text(gitignore)
    
    print("  Installing dependencies...")
    try:
        subprocess.run(
            ['npm', 'install'],
            cwd=site_dir,
            check=True,
            capture_output=True,
            text=True
        )
    except subprocess.CalledProcessError as e:
        print(f"Warning: npm install failed: {e.stderr}")
        print("You may need to run 'npm install' manually in the site directory.")
    except FileNotFoundError:
        print("Warning: npm not found. Please install dependencies manually:")
        print(f"  cd {site_dir} && npm install")
    
    print(f"\n✅ Docusaurus site initialized at {site_dir}")
    print("\nNext steps:")
    print(f"  1. Generate docs: python generate_docs.py {repo_name}")
    print(f"  2. Start dev server: cd {site_dir} && npm start")
    
    return True


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Initialize a Docusaurus site for a repository's documentation"
    )
    parser.add_argument(
        'repo_name',
        nargs='?',
        help='Repository name (defaults to auto-detection if only one repo exists)'
    )
    parser.add_argument(
        '--force', '-f',
        action='store_true',
        help='Overwrite existing site'
    )
    args = parser.parse_args()
    
    # Determine repo_name
    repo_name = args.repo_name
    if not repo_name:
        repo_name = detect_repo_name()
        if not repo_name:
            print("Error: Could not determine repo_name.")
            print("Please specify it as an argument: python init_docusaurus_site.py <repo_name>")
            print("\nAvailable repos in .docs/:")
            docs_base = Path('.docs')
            if docs_base.exists():
                for d in docs_base.iterdir():
                    if d.is_dir():
                        print(f"  - {d.name}")
            sys.exit(1)
        print(f"Auto-detected repo_name: {repo_name}")
    
    # Check if .docs/<repo_name> exists
    repo_docs_dir = Path('.docs') / repo_name
    if not repo_docs_dir.exists():
        print(f"Error: Repository docs directory not found: {repo_docs_dir}")
        print("Please run the main pipeline first to analyze the repository.")
        sys.exit(1)
    
    success = init_docusaurus_site(repo_name, args.force)
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
